# categories (site, content, ui, etc.) are described here. 
# https://docs.antora.org/antora/latest/playbook/
# A demo site example file is here. 
# https://gitlab.com/antora/demo/docs-site/-/blob/main/antora-playbook.yml

# https://gitlab.com/antora/antora-lunr-extension
antora:
  extensions:
  - '@antora/lunr-extension'
  #- require: '@antora/lunr-extension'

# https://docs.antora.org/antora/latest/playbook/configure-site/
site:
  title: Nick's Home Lab, tappity tap
  url: https://hardiman.consulting
  #start_page: infrastructure-as-code::index.adoc
  start_page: rhel8-on-pn50::index.adoc
  keys:
    google_analytics: 'G-Q3WBZX4JYP'
content:
  sources: 
  - url: https://github.com/nickhardiman/articles-fedora-rpi4.git
    branches: main
  - url: https://github.com/nickhardiman/articles-ansible.git
    branches: main
  - url: https://github.com/nickhardiman/articles-rhel8.git
    branches: main
  - url: https://github.com/nickhardiman/articles-rhel9.git
    branches: main
  - url: https://github.com/nickhardiman/articles-ocp4.git
    branches: main
  edit_url: false

# https://docs.antora.org/antora/latest/playbook/ui-bundle-url/
ui: 
  bundle:
    url: https://gitlab.com/nhardima/antora-ui-default/-/raw/master/build/ui-bundle.zip
    #url: https://github.com/nickhardiman/docs-ui/raw/main/build/ui-bundle.zip
    # https://docs.antora.org/antora/latest/playbook/ui-bundle-url/
    snapshot: true
  # supplemental_files is not properly documented. Here's something.
  # https://docs.antora.org/antora/2.3/publish-to-github-pages/#use-the-supplemental-ui
  # if the file path does not exist, this error appears. 
  #  error: problem encountered while reading ui.supplemental_files: ENOENT: no such file or directory
  supplemental_files: ./supplemental_ui

asciidoc:
  attributes:
    experimental: true 
    page-pagination: true 

runtime:
  # https://docs.antora.org/antora/latest/playbook/runtime-fetch/#fetch-key
  fetch: true

