# categories (site, content, ui and asciidoc) are described here. 
# https://docs.antora.org/antora/2.1/playbook/playbook-schema/
# A demo site example file is here. 
# https://gitlab.com/antora/demo/docs-site/-/blob/main/antora-playbook.yml
site:
  title: Nick's Home Lab, hackity hack
  url: https://rhel8-on-pn50.netlify.app
  #start_page: rhel8-on-pn50:ROOT:index.adoc
  keys:
    google_analytics: 'G-7K2RCE6KXL'
content:
  sources: 
  - url: https://github.com/nickhardiman/articles-iac.git
  - url: https://github.com/nickhardiman/articles-rhel8.git
  #  branches: main
  #  edit_url: false
# https://docs.antora.org/antora/2.3/playbook/configure-ui/
ui: 
  bundle:
    url: https://github.com/nickhardiman/antora-ui/raw/master/build/ui-bundle.zip
    snapshot: true
  supplemental_files: ./supplemental_ui
asciidoc:
  attributes:
    experimental: true 
    page-pagination: true 
runtime:
  fetch: true
